---
abstract: 'Gallery plugin for Bootylicious'
author:
  - 'Konstantin Kapitanov <perlovik@gmail.com>'
generated_by: 'Dist::Zilla version 1.093250'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bootylicious-Plugin-Gallery
requires:
  Digest::MD5: 0
  Image::Magick: 6.00
  Image::Magick::Thumbnail::Fixed: 0
  Mojo: 0.999910
version: 0.06
